#     """
#     approved_modules = ['leads', 'accounts', 'contacts', 'deals', 'campaigns', 'tasks', 'cases', 'events', 'calls',
#                         'solutions', 'products', 'vendors', 'pricebooks', 'quotes', 'salesorders', 'purchaseorders',
#                         'invoices', 'custom', 'notes', 'approvals', 'activities']
#     if module not in approved_modules:
#         return False
#     # modules_methods = {{'module': i, 'method': i()} for i in approved_modules}
#     # for i in modules_methods:
#     #     if module == i['module']:
#     #         return i['method']
#     method_to_call = getattr()
#     return
#

def leads():
    """

    :return: fields for leads module
    """
    return [{"Field Name": "Lead Owner", "API FORMAT": "Lead Owner",
             "Description": "Select the Zoho CRM user to whom the Lead is assigned.", "Data type": "Lookup",
             "Maximum Limit": ["-"]}, {"Field Name": "Salutation", "API FORMAT": "Salutation",
                                       "Description": "Select the salutation from the drop-down list.",
                                       "Data type": "Pick list", "Maximum Limit": ["-"]},
            {"Field Name": "First Name", "API FORMAT": "First Name",
             "Description": "Specify the first name of the lead.", "Data type": "Text box",
             "Maximum Limit": ["Alphanumeric(40)"]},
            {"Field Name": "Title", "API FORMAT": "Title", "Description": "Specify the job position of the lead",
             "Data type": "Text box", "Maximum Limit": ["Alphanumeric(100)"]},
            {"Field Name": "Last Name*", "API FORMAT": "Last Name*",
             "Description": "Specify the last name of the lead. This field is a mandatory.", "Data type": "Text box",
             "Maximum Limit": ["Alphanumeric(80)"]}, {"Field Name": "Company*", "API FORMAT": "Company*",
                                                      "Description": "Specify the name of the company where the lead is working. This field is a mandatory.",
                                                      "Data type": "Text box", "Maximum Limit": ["Alphanumeric(100)"]},
            {"Field Name": "Lead Source", "API FORMAT": "Lead Source",
             "Description": "Select the source of the lead, that is, from where the lead is generated.",
             "Data type": "Pick list", "Maximum Limit": ["-"]}, {"Field Name": "Industry", "API FORMAT": "Industry",
                                                                 "Description": "Select the industry to which the lead belongs.",
                                                                 "Data type": "Pick list", "Maximum Limit": ["-"]},
            {"Field Name": "Annual Revenue", "API FORMAT": "Annual Revenue",
             "Description": "Specify the annual revenue of the company where the lead is working.",
             "Data type": "Currency", "Maximum Limit": ["Decimal (16)"]},
            {"Field Name": "Phone", "API FORMAT": "Phone", "Description": "Specify the phone number of the lead.",
             "Data type": "Text box", "Maximum Limit": ["Alphanumeric(30)"]},
            {"Field Name": "Mobile", "API FORMAT": "Mobile", "Description": "Specify the mobile number of the lead.",
             "Data type": "Text box", "Maximum Limit": ["Alphanumeric(30)"]},
            {"Field Name": "Fax", "API FORMAT": "Fax", "Description": "Specify the fax number of the lead.",
             "Data type": "Text box", "Maximum Limit": ["Alphanumeric(30)"]},
            {"Field Name": "Email", "API FORMAT": "Email", "Description": "Specify the email address of the lead.",
             "Data type": "Email", "Maximum Limit": ["Alphanumeric and Special characters(100)"]},
            {"Field Name": "Secondary Email", "API FORMAT": "Secondary Email",
             "Description": "Specify another email address of the lead.", "Data type": "Email",
             "Maximum Limit": ["Alphanumeric and Special characters(100)"]},
            {"Field Name": "Skype ID", "API FORMAT": "Skype ID",
             "Description": "Specify the Skype ID of the lead. Currently skype ID can be in the range of 6 to 32 characters.",
             "Data type": "Text box", "Maximum Limit": ["Alphanumeric(50)"]},
            {"Field Name": "Website", "API FORMAT": "Website", "Description": "Specify the Web site of the lead.",
             "Data type": "URL", "Maximum Limit": ["Alphanumeric(120)"]},
            {"Field Name": "Lead Status", "API FORMAT": "Lead Status",
             "Description": "Select the status of the lead from the drop-down list.", "Data type": "Pick list",
             "Maximum Limit": ["-"]}, {"Field Name": "Rating", "API FORMAT": "Rating",
                                       "Description": "Select the rating of the lead from the drop-down list.",
                                       "Data type": "Pick list", "Maximum Limit": ["-"]},
            {"Field Name": "No. of Employees", "API FORMAT": "No. of Employees",
             "Description": "Specify the number of employees in lead's company.", "Data type": "Numeric",
             "Maximum Limit": ["Integer (16)"]}, {"Field Name": "Email Opt-out", "API FORMAT": "Email Opt-out",
                                                  "Description": "Select the check-box to remove leads from your mailing list so that they will not receive any emails from your Zoho CRM account",
                                                  "Data type": "Check box", "Maximum Limit": ["-"]},
            {"Field Name": "Street", "API FORMAT": "Street", "Description": "Specify the street address of the lead.",
             "Data type": "Text box", "Maximum Limit": ["Alphanumeric(250)"]},
            {"Field Name": "City", "API FORMAT": "City",
             "Description": "Specify the name of the city where the lead lives.", "Data type": "Text box",
             "Maximum Limit": ["Alphanumeric(30)"]}, {"Field Name": "State", "API FORMAT": "State",
                                                      "Description": "Specify the name of the state where the lead lives.",
                                                      "Data type": "Text box", "Maximum Limit": ["Alphanumeric(30)"]},
            {"Field Name": "Zip Code", "API FORMAT": "Zip Code",
             "Description": "Specify the postal code of the lead's address.", "Data type": "Numeric",
             "Maximum Limit": ["Alphanumeric(30)"]},
            {"Field Name": "Country", "API FORMAT": "Country", "Description": "Specify the name of the lead's country.",
             "Data type": "Text box", "Maximum Limit": ["Alphanumeric(30)"]},
            {"Field Name": "Description", "API FORMAT": "Description",
             "Description": "Specify any other details about the lead.", "Data type": "Text area (long text)",
             "Maximum Limit": ["32000 characters"]}]


def accounts():
    """

    :return: fields for accounts module
    """
    return [
        {"Field Name": "Field Name", "API FORMAT": "API Format", "Description": "Description", "Data type": "Data type",
         "Maximum Limit": ["Maximum Limit"]}, {"Field Name": "Account Name *", "API FORMAT": "Account Name *",
                                               "Description": "Specify the company name. This field is mandatory.",
                                               "Data type": "Text box", "Maximum Limit": ["Alphanumeric(100)"]},
        {"Field Name": "Account Owner", "API FORMAT": "Account Owner",
         "Description": "Select the name of the user to whom the account is assigned.", "Data type": "Look up",
         "Maximum Limit": ["-"]},
        {"Field Name": "Website", "API FORMAT": "Website", "Description": "Specify the URL of the company's Web site.",
         "Data type": "URL", "Maximum Limit": ["Alphanumeric(30)"]},
        {"Field Name": "Ticker Symbol", "API FORMAT": "Ticker Symbol",
         "Description": "Specify the ticker symbol of the Company.", "Data type": "Text box",
         "Maximum Limit": ["Alphanumeric(30)"]}, {"Field Name": "Parent Account", "API FORMAT": "Parent Account",
                                                  "Description": "Select the parent company name from the Change pop-up dialog.",
                                                  "Data type": "Lookup", "Maximum Limit": [""]},
        {"Field Name": "Employees", "API FORMAT": "Employees",
         "Description": "Specify the number of employees in account's company.", "Data type": "Numeric",
         "Maximum Limit": ["Integers(10)"]}, {"Field Name": "Ownership", "API FORMAT": "Ownership",
                                              "Description": "Specify the type of ownership of the company.",
                                              "Data type": "Picklist", "Maximum Limit": [""]},
        {"Field Name": "Industry", "API FORMAT": "Industry",
         "Description": "Select the type of industry from the drop-down list.", "Data type": "Pick list",
         "Maximum Limit": ["-"]}, {"Field Name": "Account Type", "API FORMAT": "Account Type",
                                   "Description": "Select the type of account from the drop-down list.",
                                   "Data type": "Pick list", "Maximum Limit": ["-"]}]


def contacts():
    """

    :return: fields for contacts module
    """
    return [{"Field Name": "Contact Owner", "API FORMAT": "Contact Owner",
             "Description": "Select the Zoho CRM user to whom the account is assigned.", "Data type": "Lookup",
             "Maximum Limit": ["-"]}, {"Field Name": "Salutation", "API FORMAT": "Salutation",
                                       "Description": "Select the Salutation of the contact, such as Mr., Ms, Mrs., or others.",
                                       "Data type": "Pick list", "Maximum Limit": [""]},
            {"Field Name": "First Name", "API FORMAT": "First Name",
             "Description": "Specify the first name of the contact.", "Data type": "Text box",
             "Maximum Limit": ["Alphanumeric(40)"]}, {"Field Name": "Last Name*", "API FORMAT": "Last Name*",
                                                      "Description": "Specify the last name of the contact. This field is mandatory.",
                                                      "Data type": "Text box", "Maximum Limit": ["Alphanumeric(40)"]},
            {"Field Name": "Account Name", "API FORMAT": "Account Name",
             "Description": "Select the account related to the contact.", "Data type": "Lookup",
             "Maximum Limit": ["-"]}, {"Field Name": "Vendor Name", "API FORMAT": "Vendor Name",
                                       "Description": "Select the vendor relatedd to the contact",
                                       "Data type": "Lookup", "Maximum Limit": ["-"]},
            {"Field Name": "Campaign Source", "API FORMAT": "Campaign Source",
             "Description": "Select the Campaign related to the contact", "Data type": "Lookup",
             "Maximum Limit": ["-"]}, {"Field Name": "Lead Source", "API FORMAT": "Lead Source",
                                       "Description": "Select the source from which the contact is created.",
                                       "Data type": "Pick list", "Maximum Limit": ["-"]},
            {"Field Name": "Title", "API FORMAT": "Title", "Description": "Specify the job position of the contact.",
             "Data type": "Text box", "Maximum Limit": ["Alphanumeric(50)"]},
            {"Field Name": "Department", "API FORMAT": "Department",
             "Description": "Specify the department of the contact.", "Data type": "Text box",
             "Maximum Limit": ["Alphanumeric(30)"]}, {"Field Name": "Date of Birth", "API FORMAT": "Date of Birth",
                                                      "Description": "Specify the birthday of the contact to send greetings for a better relationship.",
                                                      "Data type": "Date", "Maximum Limit": ["-"]},
            {"Field Name": "Reports To", "API FORMAT": "Reports To",
             "Description": "Select the person to whom the contact reports", "Data type": "Text area",
             "Maximum Limit": ["255 characters"]}, {"Field Name": "Email Opt Out", "API FORMAT": "Email Opt Out",
                                                    "Description": "Select the check-box to remove contacts from your mailing list so that they will not receive any emails from your Zoho CRM account",
                                                    "Data type": "Check box", "Maximum Limit": ["-"]},
            {"Field Name": "Skype Id", "API FORMAT": "Skype Id",
             "Description": "Specify the Skype ID of the contact. Currently skype ID can be in the range of 6 to 32 characters.",
             "Data type": "Text box", "Maximum Limit": ["Alphanumeric(50)"]},
            {"Field Name": "Phone", "API FORMAT": "Phone",
             "Description": "Specify the office phone number of the contact.", "Data type": "Text box",
             "Maximum Limit": ["Alphanumeric(50)"]},
            {"Field Name": "Mobile", "API FORMAT": "Mobile", "Description": "Specify the mobile number of the contact.",
             "Data type": "Text box", "Maximum Limit": ["Alphanumeric(50)"]},
            {"Field Name": "Home Phone", "API FORMAT": "Home Phone",
             "Description": "Specify the home phone number of the contact.", "Data type": "Text box",
             "Maximum Limit": ["Alphanumeric(50)"]}, {"Field Name": "Other Phone", "API FORMAT": "Other Phone",
                                                      "Description": "Specify the other phone number of the contact (if any).",
                                                      "Data type": "Text box", "Maximum Limit": ["Alphanumeric(50)"]},
            {"Field Name": "Fax", "API FORMAT": "Fax", "Description": "Specify the Fax number of the contact.",
             "Data type": "Text box", "Maximum Limit": ["Alphanumeric(50)"]},
            {"Field Name": "Email", "API FORMAT": "Email",
             "Description": "Specify the primary email address of the contact.", "Data type": "Email",
             "Maximum Limit": ["Alphanumeric(100)"]}, {"Field Name": "Secondary Email", "API FORMAT": "Secondary Email",
                                                       "Description": "Specify another email address of the contact.",
                                                       "Data type": "Email", "Maximum Limit": ["Alphanumeric(100)"]},
            {"Field Name": "Assistant", "API FORMAT": "Assistant",
             "Description": "Specify the name of the contact\u2019s assistant.", "Data type": "",
             "Maximum Limit": [""]}, {"Field Name": "Asst Phone", "API FORMAT": "Asst Phone",
                                      "Description": "Specify the phone number of the contact's assistant.",
                                      "Data type": "Text box", "Maximum Limit": ["Alphanumeric(100)"]},
            {"Field Name": "Mailing AddressStreet City State Zip Country",
             "API FORMAT": "Mailing AddressStreet City State Zip Country",
             "Description": "Specify the primary address of the contact.",
             "Data type": "Street - Text box City - Text box State - Text box Code - Text box Country- Text box",
             "Maximum Limit": [
                 "Alphanumeric(250) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30)"]},
            {"Field Name": "Other AddressStreet City State Zip Country",
             "API FORMAT": "Other AddressStreet City State Zip Country",
             "Description": "Specify the other address of the contact (if any).",
             "Data type": "Street - Text box City - Text box State - Text box Code - Text box Country - Text box",
             "Maximum Limit": [
                 "Alphanumeric(250) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30)"]},
            {"Field Name": "Description", "API FORMAT": "Description",
             "Description": "Specify any other details about contact.", "Data type": "Text area (long text)",
             "Maximum Limit": ["32000 characters"]}]


def calls():
    """

    :return: fields for calls module
    """
    return [{"Field Name": "Subject*", "API FORMAT": "Subject*",
             "Description": "Specify the subject of the call. This field is mandatory.", "Data type": "Text box",
             "Maximum Limit": ["Alphanumeric(50)"]}, {"Field Name": "Call Type*", "API FORMAT": "Call Type*",
                                                      "Description": "Choose whether the call is inbound or outbound",
                                                      "Data type": "", "Maximum Limit": [""]},
            {"Field Name": "Call Purpose", "API FORMAT": "Call Purpose",
             "Description": "Select the purpose of the call", "Data type": "Pick List", "Maximum Limit": [""]},
            {"Field Name": "Call From/To", "API FORMAT": "Call From/To", "Description": "Choose Contact or Lead",
             "Data type": "", "Maximum Limit": ["-"]}, {"Field Name": "Related To", "API FORMAT": "Related To",
                                                        "Description": "Select the record to which the call is related to",
                                                        "Data type": "Pick List", "Maximum Limit": ["-"]},
            {"Field Name": "Call Details", "API FORMAT": "Call Details",
             "Description": "Select whether it is a Current call or Completed call", "Data type": "",
             "Maximum Limit": ["-"]}, {"Field Name": "Call Start Time", "API FORMAT": "Call Start Time",
                                       "Description": "Automatically displays the call start data and time",
                                       "Data type": "Pick List", "Maximum Limit": [""]},
            {"Field Name": "Call Duration", "API FORMAT": "Call Duration",
             "Description": "Specify the duration of the call", "Data type": "Integer", "Maximum Limit": [""]},
            {"Field Name": "Description", "API FORMAT": "Description",
             "Description": "Specify the details about the task", "Data type": "Text area (long text)",
             "Maximum Limit": ["32000 characters"]}, {"Field Name": "Billable", "API FORMAT": "Billable",
                                                      "Description": "Select the check box if the call is considered for billing",
                                                      "Data type": "Check box", "Maximum Limit": [""]},
            {"Field Name": "Call Result", "API FORMAT": "Call Result", "Description": "Enter the call result",
             "Data type": "Text", "Maximum Limit": [""]}]


def events():
    """

    :return: fields for events module
    """
    return [{"Field Name": "Event Owner", "API FORMAT": "Event Owner",
             "Description": "Select the name of the user to whom the event is assigned.", "Data type": "Lookup",
             "Maximum Limit": [""]}, {"Field Name": "Subject*", "API FORMAT": "Subject*",
                                      "Description": "Specify the name of the event. This field is mandatory.",
                                      "Data type": "Text box", "Maximum Limit": ["Alphanumeric(50)"]},
            {"Field Name": "Start Date Time*", "API FORMAT": "Start DateTime*",
             "Description": "Specify the date and time when the event will be started. This field is mandatory.",
             "Data type": "Date and Time", "Maximum Limit": [""]},
            {"Field Name": "End Date Time *", "API FORMAT": "End DateTime *",
             "Description": "Specify the date and time when the event will be over. This field is mandatory.",
             "Data type": "Date and Time", "Maximum Limit": [""]},
            {"Field Name": "Venue", "API FORMAT": "Venue", "Description": "Enter the venue for the event",
             "Data type": "Text", "Maximum Limit": [""]},
            {"Field Name": "Contacts/Leads", "API FORMAT": "Contacts/Leads",
             "Description": "Select the related contact or lead", "Data type": "Lookup", "Maximum Limit": [""]},
            {"Field Name": "Accounts", "API FORMAT": "Accounts",
             "Description": "Select any other record related to the event", "Data type": "Lookup",
             "Maximum Limit": ["-"]}, {"Field Name": "Send Notification Email", "API FORMAT": "Send Notification Email",
                                       "Description": "Select the check box to send notification email to the event owner",
                                       "Data type": "Check box", "Maximum Limit": [""]},
            {"Field Name": "Remind At", "API FORMAT": "Remind At",
             "Description": "Select the check box to set reminder for the event", "Data type": "Check box",
             "Maximum Limit": [""]}, {"Field Name": "Recurring Activity", "API FORMAT": "Recurring Activity",
                                      "Description": "Select the check box to mark it as a recurring activity",
                                      "Data type": "Check box", "Maximum Limit": ["-"]},
            {"Field Name": "Description", "API FORMAT": "Description",
             "Description": "Specify the details about the event", "Data type": "Text area (long text)",
             "Maximum Limit": ["32000 characters"]}]


def tasks():
    """

    :return: fields for tasks module
    """
    return [{"Field Name": "Task Owner", "API FORMAT": "Task Owner",
             "Description": "Select the name of the user to whom the task is assigned.", "Data type": "Lookup",
             "Maximum Limit": ""}, {"Field Name": "Subject*", "API FORMAT": "Subject*",
                                    "Description": "Specify the name of the task. This field is mandatory.",
                                    "Data type": "Text box", "Maximum Limit": "Alphanumeric(50)"},
            {"Field Name": "Due Date", "API FORMAT": "Due Date", "Description": "Specify the due date for the task",
             "Data type": "Date", "Maximum Limit": ""}, {"Field Name": "Contacts/Leads", "API FORMAT": "Contacts/Leads",
                                                         "Description": "Select the related contact or lead",
                                                         "Data type": "Lookup", "Maximum Limit": ""},
            {"Field Name": "Accounts", "API FORMAT": "Accounts",
             "Description": "Select any other record related to the task", "Data type": "Lookup", "Maximum Limit": "-"},
            {"Field Name": "Status", "API FORMAT": "Status", "Description": "Specify the status of the task",
             "Data type": "Pick List", "Maximum Limit": "-"},
            {"Field Name": "Priority", "API FORMAT": "Priority", "Description": "Select the due date.",
             "Data type": "Date", "Maximum Limit": "-"},
            {"Field Name": "Send Notification Email", "API FORMAT": "Send Notification Email",
             "Description": "Select the check box to send notification email to the task owner",
             "Data type": "Check box", "Maximum Limit": ""}, {"Field Name": "Remind At", "API FORMAT": "Remind At",
                                                              "Description": "Select the check box to set reminder for the task",
                                                              "Data type": "Check box", "Maximum Limit": ""},
            {"Field Name": "Recurring Activity", "API FORMAT": "Recurring Activity",
             "Description": "Select the check box to mark it as a recurring activity", "Data type": "Check box",
             "Maximum Limit": "-"}, {"Field Name": "Description", "API FORMAT": "Description",
                                     "Description": "Specify the details about the task",
                                     "Data type": "Text area (long text)", "Maximum Limit": "32000 characters"}, ]


def purchaseorders():
    """
    
    :return: fields for purchase order module 
    """
    return [{"Field Name": "Purchase Order Owner", "API FORMAT": "Purchase Order Owner",
             "Description": "Select the name of the user to whom the purchase order is assigned.",
             "Data type": "Lookup", "Maximum Limit": ""}, {"Field Name": "PO Number", "API FORMAT": "PO Number",
                                                           "Description": "Display the Sales order ID after creating a case.",
                                                           "Data type": "Number", "Maximum Limit": "16 digit"},
            {"Field Name": "Subject*", "API FORMAT": "Subject*",
             "Description": "Specify the name of the purchase order. This field is mandatory.", "Data type": "Text box",
             "Maximum Limit": "Alphanumeric(50)"}, {"Field Name": "Vendor Name*", "API FORMAT": "Vendor Name*",
                                                    "Description": "Specify the name of the vendor.",
                                                    "Data type": "Text box", "Maximum Limit": "Alphanumeric(20)"},
            {"Field Name": "Requisition No", "API FORMAT": "Requisition No",
             "Description": "Specify the number in which the purchase order is requested", "Data type": "Text box",
             "Maximum Limit": "Alphanumeric(20)"}, {"Field Name": "Tracking Number", "API FORMAT": "Tracking Number",
                                                    "Description": "Specify the number to track the purchase order",
                                                    "Data type": "Text box", "Maximum Limit": ""},
            {"Field Name": "Contact Name", "API FORMAT": "Contact Name",
             "Description": "Specify the contacts name to which the invoice has to be created.", "Data type": "Lookup",
             "Maximum Limit": ""}, {"Field Name": "Carrier", "API FORMAT": "Carrier",
                                    "Description": "Select the carriers name that ships the products from your warehouse to customer site.",
                                    "Data type": "Pick list", "Maximum Limit": "-"},
            {"Field Name": "Purchase Order Date", "API FORMAT": "Purchase Order Date",
             "Description": "Specify the date on which purchase order is created.", "Data type": "Date",
             "Maximum Limit": "-"},
            {"Field Name": "Due Date", "API FORMAT": "Due Date", "Description": "Select the due date.",
             "Data type": "Date", "Maximum Limit": "-"}, {"Field Name": "Excise Duty", "API FORMAT": "Excise Duty",
                                                          "Description": "Specify the excise duty for the shipment",
                                                          "Data type": "Text box", "Maximum Limit": ""},
            {"Field Name": "Sales Commission", "API FORMAT": "Sales Commission",
             "Description": "Specify the commission to the sales person upon closing the deal.",
             "Data type": "Currency", "Maximum Limit": "Float"},
            {"Field Name": "Status", "API FORMAT": "Status", "Description": "Specify the status of the purchase order.",
             "Data type": "Check box", "Maximum Limit": "-"}, {"Field Name": "Assigned To", "API FORMAT": "Assigned To",
                                                               "Description": "Select the Zoho CRM user name to whom the purchase order handling duty is assigned. This field is mandatory",
                                                               "Data type": "Select option", "Maximum Limit": "-"},
            {"Field Name": "Billing AddressStreet City State Zip Country",
             "API FORMAT": "Billing AddressStreet City State Zip Country",
             "Description": "Specify the primary address of the contact.",
             "Data type": "Street - Text box City - Text box State - Text box Code - Text box Country- Text box",
             "Maximum Limit": "Alphanumeric(250) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30)"},
            {"Field Name": "Shipping AddressStreet City State Zip Country",
             "API FORMAT": "Shipping AddressStreet City State Zip Country",
             "Description": "Specify the shipping address of the contact (if any).",
             "Data type": "Street - Text box City - Text box State - Text box Code - Text box Country - Text box",
             "Maximum Limit": "Alphanumeric(250) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30)"},
            {"Field Name": "Product Name *", "API FORMAT": "Product Name *",
             "Description": "Select the product name.This field is mandatory", "Data type": "Lookup",
             "Maximum Limit": "-"}, {"Field Name": "Quantity in Stock", "API FORMAT": "Quantity in Stock",
                                     "Description": "Displays the stock quantity.", "Data type": "Numeric",
                                     "Maximum Limit": "Integers"},
            {"Field Name": "Quantity*", "API FORMAT": "Quantity*",
             "Description": "Specify the quantity for which the sales order has to be generated. This field is mandatory",
             "Data type": "Numeric", "Maximum Limit": "Integers"},
            {"Field Name": "Unit Price*", "API FORMAT": "Unit Price*",
             "Description": "Displays the unit price of the product.", "Data type": "Currency", "Maximum Limit": ""},
            {"Field Name": "List Price*", "API FORMAT": "List Price*",
             "Description": "Select the product list price from Price Book or specify the product price. This field is mandatory",
             "Data type": "Lookup and Numeric", "Maximum Limit": "Integers"},
            {"Field Name": "Total", "API FORMAT": "Total",
             "Description": "Displays the amount of the selected products.", "Data type": "", "Maximum Limit": ""},
            {"Field Name": "Terms & Conditions", "API FORMAT": "Terms & Conditions",
             "Description": "Specify the terms and conditions that are associated with purchase order.",
             "Data type": "Text area (long text)", "Maximum Limit": ""},
            {"Field Name": "Description", "API FORMAT": "Description",
             "Description": "Specify any other details about purchase order.", "Data type": "Text area (long text)",
             "Maximum Limit": "32000 characters"}

            ]


def vendors():
    """

    :return: fields for vendors module
    """
    return [{"Field Name": "Vendor Owner", "API FORMAT": "Vendor Owner",
             "Description": "Select the name of the user to whom the Vendor details is assigned.",
             "Data type": "Lookup", "Maximum Limit": ""}, {"Field Name": "Vendor Name*", "API FORMAT": "Vendor Name*",
                                                           "Description": "Specify the name of the vendor. This field is mandatory",
                                                           "Data type": "Text box",
                                                           "Maximum Limit": "Alphanumeric(50)"},
            {"Field Name": "Phone", "API FORMAT": "Phone", "Description": "Specify the phone number of the vendor",
             "Data type": "Text box", "Maximum Limit": "Alphanumeric(40)"},
            {"Field Name": "E-mail", "API FORMAT": "E-mail", "Description": "Specify the E-mail ID of the vendor",
             "Data type": "Email", "Maximum Limit": "Alphanumeric and Special characters(100)"},
            {"Field Name": "Website", "API FORMAT": "Website", "Description": "Specify the Web site URL of the vendor",
             "Data type": "URL", "Maximum Limit": "Alphanumeric and Special characters(50)"},
            {"Field Name": "GL Account", "API FORMAT": "GL Account", "Description": "Select the general ledger account",
             "Data type": "Pick List", "Maximum Limit": "-"},
            {"Field Name": "Category", "API FORMAT": "Category", "Description": "Specify the category of the vendor",
             "Data type": "Text box", "Maximum Limit": "Alphanumeric(40)"},
            {"Field Name": "Vendor AddressStreet City State Postal Code Country",
             "API FORMAT": "Vendor AddressStreet City State Postal Code Country",
             "Description": "Specify the address of the vendor",
             "Data type": "Street - Text box City - Text box State - Text box Code - Text box Country- Text box",
             "Maximum Limit": "Alphanumeric(250) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30)"},
            {"Field Name": "Description", "API FORMAT": "Description",
             "Description": "Specify any other details about vendor", "Data type": "Text area (long text)",
             "Maximum Limit": "32000 characters"}

            ]


def invoices():
    """

    :return: fields for invoices module
    """
    return [{"Field Name": "Invoice Owner", "API FORMAT": "Invoice Owner",
             "Description": "Select the name of the user to whom the invoice is assigned.", "Data type": "Lookup",
             "Maximum Limit": ""}, {"Field Name": "Invoice Number", "API FORMAT": "Invoice Number",
                                    "Description": "Display the case ID after creating a solution",
                                    "Data type": "Numeric", "Maximum Limit": "16 digit"},
            {"Field Name": "Subject*", "API FORMAT": "Subject*",
             "Description": "Specify the name of the invoice. This field is mandatory.", "Data type": "Text box",
             "Maximum Limit": "Alphanumeric(50)"}, {"Field Name": "Sales Order", "API FORMAT": "Sales Order",
                                                    "Description": "Select the reference Sales order (if any).",
                                                    "Data type": "Lookup", "Maximum Limit": "-"},
            {"Field Name": "Purchase Order", "API FORMAT": "Purchase Order",
             "Description": "Select the reference Purchase order.", "Data type": "Text Box", "Maximum Limit": ""},
            {"Field Name": "Customer No", "API FORMAT": "Customer No",
             "Description": "Specify the customer identification number (if any).", "Data type": "Text box",
             "Maximum Limit": "Alphanumeric(50)"}, {"Field Name": "Excise Duty", "API FORMAT": "Excise Duty",
                                                    "Description": "Specify the excise duty for the shipment",
                                                    "Data type": "Text box", "Maximum Limit": "Numeric"},
            {"Field Name": "Invoice Date", "API FORMAT": "Invoice Date",
             "Description": "Specify the date on which the invoice is created.", "Data type": "Date",
             "Maximum Limit": "-"}, {"Field Name": "Due Date", "API FORMAT": "Due Date",
                                     "Description": "Specify the invoice due date as per your payment terms.",
                                     "Data type": "Date", "Maximum Limit": "-"},
            {"Field Name": "Sales Commission", "API FORMAT": "Sales Commission",
             "Description": "Specify the commission to the sales person upon closing the deal.",
             "Data type": "Currency", "Maximum Limit": "Float"},
            {"Field Name": "Account Name *", "API FORMAT": "Account Name *",
             "Description": "Specify the account name to which the invoice has to be created. This field is mandatory",
             "Data type": "Lookup", "Maximum Limit": "-"}, {"Field Name": "Contact Name", "API FORMAT": "Contact Name",
                                                            "Description": "Specify the contacts name to which the invoice has to be created.",
                                                            "Data type": "Lookup", "Maximum Limit": ""},
            {"Field Name": "Status", "API FORMAT": "Status", "Description": "Specify the status of the invoice.",
             "Data type": "Check box", "Maximum Limit": "-"}, {"Field Name": "Assigned To", "API FORMAT": "Assigned To",
                                                               "Description": "Select the user's name to whom the invoice handling duty is assigned.This field is mandatory",
                                                               "Data type": "Lookup", "Maximum Limit": "-"},
            {"Field Name": "Billing AddressStreet City State Zip Country",
             "API FORMAT": "Billing AddressStreet City State Zip Country",
             "Description": "Specify the primary address of the contact.",
             "Data type": "Street - Text box City - Text box State - Text box Code - Text box Country- Text box",
             "Maximum Limit": "Alphanumeric(250) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30)"},
            {"Field Name": "Shipping AddressStreet City State Zip Country",
             "API FORMAT": "Shipping AddressStreet City State Zip Country",
             "Description": "Specify the shipping address of the contact (if any).",
             "Data type": "Street - Text box City - Text box State - Text box Code - Text box Country - Text box",
             "Maximum Limit": "Alphanumeric(250) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30)"},
            {"Field Name": "Product Name *", "API FORMAT": "Product Name *",
             "Description": "Select the product name.This field is mandatory", "Data type": "Lookup",
             "Maximum Limit": "-"}, {"Field Name": "Quantity in Stock", "API FORMAT": "Quantity in Stock",
                                     "Description": "Displays the stock quantity.", "Data type": "Numeric",
                                     "Maximum Limit": "Integers"},
            {"Field Name": "Quantity*", "API FORMAT": "Quantity*",
             "Description": "Specify the quantity for which the sales order has to be generated. This field is mandatory",
             "Data type": "Numeric", "Maximum Limit": "Integers"},
            {"Field Name": "Unit Price*", "API FORMAT": "Unit Price*",
             "Description": "Displays the unit price of the product.", "Data type": "Currency", "Maximum Limit": ""},
            {"Field Name": "List Price*", "API FORMAT": "List Price*",
             "Description": "Select the product list price from Price Book or specify the product price. This field is mandatory",
             "Data type": "Lookup and Numeric", "Maximum Limit": "Integers"},
            {"Field Name": "Total", "API FORMAT": "Total",
             "Description": "Displays the amount of the selected products.", "Data type": "Currency",
             "Maximum Limit": "-"}, {"Field Name": "Terms & Conditions", "API FORMAT": "Terms & Conditions",
                                     "Description": "Specify the terms and conditions that are associated with invoice.",
                                     "Data type": "Text area", "Maximum Limit": ""},
            {"Field Name": "Description", "API FORMAT": "Description",
             "Description": "Specify any other details about invoice.", "Data type": "Text area",
             "Maximum Limit": "32000 characters"}

            ]


def salesorders():
    """

    :return: fields for sales order module
    """
    return [{"Field Name": "Sales Order Owner", "API FORMAT": "Sales Order Owner",
             "Description": "Select the name of the user to whom the sales order is assigned.", "Data type": "Lookup",
             "Maximum Limit": ""}, {"Field Name": "SO Number", "API FORMAT": "SO Number",
                                    "Description": "Display the Sales order ID after creating a case.",
                                    "Data type": "Number", "Maximum Limit": "16 digit"},
            {"Field Name": "Subject*", "API FORMAT": "Subject*",
             "Description": "Specify the name of the sales order. This field is mandatory.", "Data type": "Text box",
             "Maximum Limit": "Alphanumeric(50)"}, {"Field Name": "Deal Name", "API FORMAT": "Deal Name",
                                                    "Description": "Select the Deal for which the sales order has to be generated.",
                                                    "Data type": "Lookup", "Maximum Limit": "-"},
            {"Field Name": "Customer No", "API FORMAT": "Customer No",
             "Description": "Specify the customer identification number (if any)", "Data type": "Text box",
             "Maximum Limit": "Alphanumeric(50)"}, {"Field Name": "Purchase Order", "API FORMAT": "Purchase Order",
                                                    "Description": "Select the reference purchase order.",
                                                    "Data type": "Text box", "Maximum Limit": "-"},
            {"Field Name": "Quote Name", "API FORMAT": "Quote Name", "Description": "Select the reference quote.",
             "Data type": "Lookup", "Maximum Limit": "-"}, {"Field Name": "Contact Name", "API FORMAT": "Contact Name",
                                                            "Description": "Select the contact for which the sales order has to be generated.",
                                                            "Data type": "Lookup", "Maximum Limit": "-"},
            {"Field Name": "Due Date", "API FORMAT": "Due Date", "Description": "Select the date", "Data type": "Date",
             "Maximum Limit": "-"}, {"Field Name": "Carrier", "API FORMAT": "Carrier",
                                     "Description": "Select the carriers name that ships the products from your warehouse to customer site.",
                                     "Data type": "Pick list", "Maximum Limit": "-"},
            {"Field Name": "Pending", "API FORMAT": "Pending", "Description": "", "Data type": "Text box",
             "Maximum Limit": "Alphanumeric(50)"},
            {"Field Name": "Status", "API FORMAT": "Status", "Description": "Specify the status of the sales order.",
             "Data type": "Pick list", "Maximum Limit": "-"},
            {"Field Name": "Sales Commission", "API FORMAT": "Sales Commission",
             "Description": "Specify the commission to the sales person upon closing the deal.", "Data type": "Numeric",
             "Maximum Limit": "float"}, {"Field Name": "Excise Duty", "API FORMAT": "Excise Duty",
                                         "Description": "Specify the excise duty for the shipment",
                                         "Data type": "Text Box", "Maximum Limit": "Numeric"},
            {"Field Name": "Account Name*", "API FORMAT": "Account Name*",
             "Description": "Specify the account name to which the sales order has to be created.This field is mandatory",
             "Data type": "Lookup", "Maximum Limit": "-"}, {"Field Name": "Assigned To", "API FORMAT": "Assigned To",
                                                            "Description": "Select the user's name to whom the sales order handling duty is assigned.",
                                                            "Data type": "Select option", "Maximum Limit": "-"},
            {"Field Name": "Billing AddressStreet City State Zip Country",
             "API FORMAT": "Billing AddressStreet City State Zip Country",
             "Description": "Specify the primary address of the contact.",
             "Data type": "Street - Text box City - Text box State - Text box Code - Text box Country- Text box",
             "Maximum Limit": "Alphanumeric(250) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30)"},
            {"Field Name": "Shipping AddressStreet City State Zip Country",
             "API FORMAT": "Shipping AddressStreet City State Zip Country",
             "Description": "Specify the shipping address of the contact (if any).",
             "Data type": "Street - Text box City - Text box State - Text box Code - Text box Country - Text box",
             "Maximum Limit": "Alphanumeric(250) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30)"},
            {"Field Name": "Product Name *", "API FORMAT": "Product Name *",
             "Description": "Select the product name.This field is mandatory", "Data type": "Lookup",
             "Maximum Limit": "-"}, {"Field Name": "Quantity in Stock", "API FORMAT": "Quantity in Stock",
                                     "Description": "Displays the stock quantity.", "Data type": "Numeric",
                                     "Maximum Limit": "Integers"},
            {"Field Name": "Quantity*", "API FORMAT": "Quantity*",
             "Description": "Specify the quantity for which the sales order has to be generated. This field is mandatory",
             "Data type": "Numeric", "Maximum Limit": "Integers"},
            {"Field Name": "Unit Price*", "API FORMAT": "Unit Price*",
             "Description": "Displays the unit price of the product.", "Data type": "Currency", "Maximum Limit": ""},
            {"Field Name": "List Price*", "API FORMAT": "List Price*",
             "Description": "Select the product list price from Price Book or specify the product price. This field is mandatory",
             "Data type": "Lookup and Numeric", "Maximum Limit": "Integers"},
            {"Field Name": "Tax", "API FORMAT": "Tax", "Description": "Specify the tax component of the products",
             "Data type": "Currency", "Maximum Limit": "-"}, {"Field Name": "Adjustments", "API FORMAT": "Adjustments",
                                                              "Description": "Specify if there are any adjustments, such as discounts, or extra charges etc.",
                                                              "Data type": "Currency", "Maximum Limit": "-"},
            {"Field Name": "Total", "API FORMAT": "Total",
             "Description": "Displays the amount of the selected line item.", "Data type": "Currency",
             "Maximum Limit": "-"}, {"Field Name": "Terms & Conditions", "API FORMAT": "Terms & Conditions",
                                     "Description": "Specify the terms and conditions that are associated with sales order.",
                                     "Data type": "Text area (long text)", "Maximum Limit": ""},
            {"Field Name": "Description", "API FORMAT": "Description",
             "Description": "Specify any other details about sales order.", "Data type": "Text area (long text)",
             "Maximum Limit": "32000 characters"}

            ]


def quotes():
    """

    :return: fields for quotes module
    """
    return [{"Field Name": "Quote Owner", "API FORMAT": "Quote Owner",
             "Description": "Select the name of the user to whom the quote is assigned.", "Data type": "Lookup",
             "Maximum Limit": "-"}, {"Field Name": "Subject*", "API FORMAT": "Subject*",
                                     "Description": "Specify the name of the quote. This field is mandatory.",
                                     "Data type": "Text box", "Maximum Limit": "Alphanumeric(50)"},
            {"Field Name": "Deal Name", "API FORMAT": "Deal Name",
             "Description": "Specify the Deal name for which the quote has to be created.", "Data type": "Text box",
             "Maximum Limit": "Alphanumeric(40)"}, {"Field Name": "Quote Stage", "API FORMAT": "Quote Stage",
                                                    "Description": "Specify the status of the quote.",
                                                    "Data type": "Check box", "Maximum Limit": "-"},
            {"Field Name": "Valid Till", "API FORMAT": "Valid Till",
             "Description": "Specify the date till the quote is valid after sending to the prospective customer.",
             "Data type": "Date", "Maximum Limit": "-"}, {"Field Name": "Contact Name", "API FORMAT": "Contact Name",
                                                          "Description": "Specify the contact to which the quote has to be created.",
                                                          "Data type": "Lookup", "Maximum Limit": "-"},
            {"Field Name": "Account Name", "API FORMAT": "Account Name",
             "Description": "Specify the account to which the quote has to be created.", "Data type": "Lookup",
             "Maximum Limit": ""}, {"Field Name": "Carrier", "API FORMAT": "Carrier",
                                    "Description": "Select the name of the carrier manufacturer.",
                                    "Data type": "Pick list", "Maximum Limit": "-"},
            {"Field Name": "Shipping", "API FORMAT": "Shipping", "Description": "Select the category of the quote.",
             "Data type": "Text box", "Maximum Limit": "Alphanumeric(50)"},
            {"Field Name": "Inventory Manager", "API FORMAT": "Inventory Manager",
             "Description": "Specify the person responsible for shipping the shipment to the account or contact.",
             "Data type": "Text box", "Maximum Limit": "Alphanumeric(50)"},
            {"Field Name": "Account Name*", "API FORMAT": "Account Name*",
             "Description": "Specify the account name to which the quote has to be created. This field is mandatory",
             "Data type": "Lookup", "Maximum Limit": ""}, {"Field Name": "Billing AddressStreet City State Zip Country",
                                                           "API FORMAT": "Billing AddressStreet City State Zip Country",
                                                           "Description": "Specify the primary address of the contact.",
                                                           "Data type": "Street - Text box City - Text box State - Text box Code - Text box Country- Text box",
                                                           "Maximum Limit": "Alphanumeric(250) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30)"},
            {"Field Name": "Shipping AddressStreet City State Zip Country",
             "API FORMAT": "Shipping AddressStreet City State Zip Country",
             "Description": "Specify the shipping address of the contact (if any).",
             "Data type": "Street - Text box City - Text box State - Text box Code - Text box Country - Text box",
             "Maximum Limit": "Alphanumeric(250) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30) Alphanumeric(30)"},
            {"Field Name": "Product Name *", "API FORMAT": "Product Name *",
             "Description": "Select the product name.This field is mandatory", "Data type": "Lookup",
             "Maximum Limit": "-"}, {"Field Name": "Quantity in Stock", "API FORMAT": "Quantity in Stock",
                                     "Description": "Displays the stock quantity.", "Data type": "Numeric",
                                     "Maximum Limit": "Integers"},
            {"Field Name": "Quantity*", "API FORMAT": "Quantity*",
             "Description": "Specify the quantity for which the sales order has to be generated. This field is mandatory",
             "Data type": "Numeric", "Maximum Limit": "Integers"},
            {"Field Name": "Unit Price*", "API FORMAT": "Unit Price*",
             "Description": "Displays the unit price of the product.", "Data type": "Currency", "Maximum Limit": ""},
            {"Field Name": "List Price*", "API FORMAT": "List Price*",
             "Description": "Select the product list price from Price Book or specify the product price. This field is mandatory",
             "Data type": "Lookup and Numeric", "Maximum Limit": "Integers"},
            {"Field Name": "Total", "API FORMAT": "Total",
             "Description": "Displays the amount of the selected products.", "Data type": "Text box",
             "Maximum Limit": "Alphanumeric"}, {"Field Name": "Terms & Conditions", "API FORMAT": "Terms & Conditions",
                                                "Description": "Specify the terms and conditions that are associated with quote.",
                                                "Data type": "Text area", "Maximum Limit": ""},
            {"Field Name": "Description", "API FORMAT": "Description",
             "Description": "Specify any other details about quote.", "Data type": "Text area",
             "Maximum Limit": "32000 characters"}

            ]


def pricebooks():
    """

    :return: fields for price_books module
    """
    return [{"Field Name": "Price Book Owner", "API FORMAT": "Price Book Owner",
             "Description": "Select the name of the user to whom the price book is assigned.", "Data type": "Lookup",
             "Maximum Limit": "-"}, {"Field Name": "Price Book Name*", "API FORMAT": "Price Book Name*",
                                     "Description": "Specify the name of the Price Book. This field is mandatory.",
                                     "Data type": "Text box", "Maximum Limit": "Alphanumeric(50)"},
            {"Field Name": "Active", "API FORMAT": "Active",
             "Description": "Select the Active check box to set the status of the Price Book as active.",
             "Data type": "Check box", "Maximum Limit": "-"},
            {"Field Name": "Pricing Model", "API FORMAT": "Pricing Model",
             "Description": "Select the model of the price book", "Data type": "Pick list", "Maximum Limit": "-"},
            {"Field Name": "Description", "API FORMAT": "Description",
             "Description": "Specify any other details about Price Book.", "Data type": "Text area (long text)",
             "Maximum Limit": "32000characters"}, {"Field Name": "Pricing DetailsFrom Range To Range Discount",
                                                   "API FORMAT": "Pricing DetailsFrom Range To Range Discount",
                                                   "Description": "Specify the Pricing details",
                                                   "Data type": "From Range - Text box To Range - Text box Discount - Percent",
                                                   "Maximum Limit": "Decimal (20)"}

            ]


def products():
    """

    :return: fields for products module
    """
    return [{"Field Name": "Product Name*", "API FORMAT": "Product Name*",
             "Description": "Specify the name of the product. This field is mandatory.", "Data type": "Text box",
             "Maximum Limit": "Alphanumeric(50)"}, {"Field Name": "Product Owner", "API FORMAT": "Product Owner",
                                                    "Description": "Select the name of the user to whom the product is assigned.",
                                                    "Data type": "Pick list", "Maximum Limit": ""},
            {"Field Name": "Product Code", "API FORMAT": "Product Code",
             "Description": "Specify the product identification.", "Data type": "Text box",
             "Maximum Limit": "Alphanumeric(40)"}, {"Field Name": "Product Active", "API FORMAT": "Product Active",
                                                    "Description": "Specify the status of the product.",
                                                    "Data type": "Check box", "Maximum Limit": "-"},
            {"Field Name": "Vendor Name", "API FORMAT": "Vendor Name", "Description": "Specify the name of the vendor.",
             "Data type": "Lookup", "Maximum Limit": ""},
            {"Field Name": "Product Category", "API FORMAT": "Product Category",
             "Description": "Select the category of the product.", "Data type": "Pick list", "Maximum Limit": ""},
            {"Field Name": "Sales Start Date", "API FORMAT": "Sales Start Date",
             "Description": "Specify the date on which the product sales starts", "Data type": "Date",
             "Maximum Limit": ""}, {"Field Name": "Sales End Date", "API FORMAT": "Sales End Date",
                                    "Description": "Specify the date on which the product sales ends",
                                    "Data type": "Date", "Maximum Limit": ""},
            {"Field Name": "Commission Rate", "API FORMAT": "Commission Rate",
             "Description": "Specify the commission rate for selling the product.", "Data type": "Numeric",
             "Maximum Limit": "Decimal"}, {"Field Name": "Manufacturer", "API FORMAT": "Manufacturer",
                                           "Description": "Select the name of the product manufacturer.",
                                           "Data type": "Pick list", "Maximum Limit": "-"},
            {"Field Name": "Unit Price", "API FORMAT": "Unit Price",
             "Description": "Specify the unit price of the product.", "Data type": "Currency", "Maximum Limit": ""},
            {"Field Name": "Taxable", "API FORMAT": "Taxable",
             "Description": "Specify whether the product is a taxable product", "Data type": "Check-box",
             "Maximum Limit": ""}, {"Field Name": "Product Category", "API FORMAT": "Product Category",
                                    "Description": "Select the category of the product.", "Data type": "Pick list",
                                    "Maximum Limit": "-"},
            {"Field Name": "Support Start Date", "API FORMAT": "Support Start Date",
             "Description": "Select the date on which the product support starts.", "Data type": "Date",
             "Maximum Limit": "-"}, {"Field Name": "Support Expiry Date", "API FORMAT": "Support Expiry Date",
                                     "Description": "Select the date on which the product support ends.",
                                     "Data type": "Date", "Maximum Limit": "-"},
            {"Field Name": "Usage Unit", "API FORMAT": "Usage Unit",
             "Description": "Displays the unit price of the product.", "Data type": "Text box",
             "Maximum Limit": "Alphanumeric"},
            {"Field Name": "Qty Ordered", "API FORMAT": "Qty Ordered", "Description": "Specify the number of units.",
             "Data type": "Text box", "Maximum Limit": "Integers"},
            {"Field Name": "Qty in Stock", "API FORMAT": "Qty in Stock", "Description": "Displays the stock quantity",
             "Data type": "Text box", "Maximum Limit": "Integers"},
            {"Field Name": "Reorder Level", "API FORMAT": "Reorder Level", "Description": "Specify the Reorder value",
             "Data type": "Text box", "Maximum Limit": "Integers"}, {"Field Name": "Handler", "API FORMAT": "Handler",
                                                                     "Description": "Select the Zoho CRM user who is handling the product",
                                                                     "Data type": "Lookup", "Maximum Limit": ""},
            {"Field Name": "Qty in Demand", "API FORMAT": "Qty in Demand",
             "Description": "Displays the demand quantity", "Data type": "Text box", "Maximum Limit": "Integers"},
            {"Field Name": "Description", "API FORMAT": "Description",
             "Description": "Specify any other details about product.", "Data type": "Text area (long text)",
             "Maximum Limit": "32000 characters"}

            ]


def solutions():
    """

    :return: fields for solutions module
    """
    return [{"Field Name": "Solution Number", "API FORMAT": "Solution Number",
             "Description": "Display the case ID after creating a solution", "Data type": "Number",
             "Maximum Limit": "16 digit"}, {"Field Name": "Solution Title*", "API FORMAT": "Solution Title*",
                                            "Description": "Specify the subject of the solution.This field is mandatory",
                                            "Data type": "Text box", "Maximum Limit": "Alphanumeric(255)"},
            {"Field Name": "Solution Owner", "API FORMAT": "Solution Owner",
             "Description": "Select the name of the user to whom the solution is assigned.", "Data type": "Pick list",
             "Maximum Limit": "-"}, {"Field Name": "Product Name", "API FORMAT": "Product Name",
                                     "Description": "Select the name of the product to which the solution has to be associated.",
                                     "Data type": "Lookup", "Maximum Limit": "-"},
            {"Field Name": "Question*", "API FORMAT": "Question*",
             "Description": "Select the priority of the solution from the drop-down list.This field is mandatory",
             "Data type": "Text box, Alphanumeric", "Maximum Limit": "Alphanumeric(255)"},
            {"Field Name": "Answer*", "API FORMAT": "Answer*",
             "Description": "Specify solution details.This field is mandatory", "Data type": "Text Area",
             "Maximum Limit": "-"},
            {"Field Name": "Status", "API FORMAT": "Status", "Description": "Specify the status of the solution.",
             "Data type": "Pick list", "Maximum Limit": "-"}, {"Field Name": "Description", "API FORMAT": "Description",
                                                               "Description": "Specify any other details about solution.",
                                                               "Data type": "Text box",
                                                               "Maximum Limit": "32000 characters"},
            {"Field Name": "Comments", "API FORMAT": "Comments",
             "Description": "Specify additional comments about the solution.", "Data type": "Text box",
             "Maximum Limit": "32000 characters"}

            ]


def sales():
    """

    :return: fields for sales module
    """
    return [{"Field Name": "Case Number", "API FORMAT": "Case Number",
             "Description": "Display the case ID after creating a case.", "Data type": "Number",
             "Maximum Limit": "16 digit"}, {"Field Name": "Product Name", "API FORMAT": "Product Name",
                                            "Description": "Select the product name related to the case.",
                                            "Data type": "Lookup", "Maximum Limit": "-"},
            {"Field Name": "Case Owner", "API FORMAT": "Case Owner",
             "Description": "Select the name of the user to whom the case is assigned.", "Data type": "Lookup",
             "Maximum Limit": "-"}, {"Field Name": "Subject*", "API FORMAT": "Subject*",
                                     "Description": "Specify the title of the Case. This field is mandatory.",
                                     "Data type": "Text box", "Maximum Limit": "Alphanumeric(255)"},
            {"Field Name": "Priority", "API FORMAT": "Priority",
             "Description": "Select the priority of the Case from the drop-down list.", "Data type": "Pick list",
             "Maximum Limit": "-"}, {"Field Name": "Status*", "API FORMAT": "Status*",
                                     "Description": "Select the status of the Case from the drop-down list.",
                                     "Data type": "Pick list", "Maximum Limit": "-"},
            {"Field Name": "Reported By", "API FORMAT": "Reported By",
             "Description": "Displays the name of the contact.", "Data type": "-", "Maximum Limit": "-"},
            {"Field Name": "Related To", "API FORMAT": "Related To",
             "Description": "Select the name of the contact who submitted the Case.", "Data type": "Lookup",
             "Maximum Limit": "-"}, {"Field Name": "Type", "API FORMAT": "Type",
                                     "Description": "Select the type of problem. It can be a general question, feature request, or real issue in your product/service.",
                                     "Data type": "Pick list", "Maximum Limit": "-"},
            {"Field Name": "Case Origin*", "API FORMAT": "Case Origin*",
             "Description": "Select the source from which the case has been generated. You can select Email, Phone, or Website. If you select Email, you must specify the Email ID of the customer.",
             "Data type": "Pick list", "Maximum Limit": "-"},
            {"Field Name": "Email", "API FORMAT": "Email", "Description": "Specify the Email ID of the contact.",
             "Data type": "Email", "Maximum Limit": "Alphanumeric and Special characters"},
            {"Field Name": "Account Name", "API FORMAT": "Account Name",
             "Description": "Select the account related to the case", "Data type": "Lookup", "Maximum Limit": ""},
            {"Field Name": "Deal Name", "API FORMAT": "Deal Name", "Description": "Select the Deal related to the case",
             "Data type": "Lookup", "Maximum Limit": ""},
            {"Field Name": "Phone", "API FORMAT": "Phone", "Description": "Specify the phone number of the customer",
             "Data type": "Text box", "Maximum Limit": "Alphanumeric(50)"},
            {"Field Name": "Case Reason", "API FORMAT": "Case Reason", "Description": "Specify the reason for the case",
             "Data type": "Pick list", "Maximum Limit": "-"}, {"Field Name": "Description", "API FORMAT": "Description",
                                                               "Description": "Specify complete details about the case.",
                                                               "Data type": "Text Area",
                                                               "Maximum Limit": "32000 characters"},
            {"Field Name": "Internal Comments", "API FORMAT": "Internal Comments",
             "Description": "Specify follow-up notes about case.", "Data type": "Text Area",
             "Maximum Limit": "3000 characters"},
            {"Field Name": "Solution", "API FORMAT": "Solution", "Description": "Specify the solution provided",
             "Data type": "Text Area", "Maximum Limit": "32000 characters"},
            {"Field Name": "Add Comment", "API FORMAT": "Add Comment",
             "Description": "specify the follow-up notes about the solution", "Data type": "Text Area",
             "Maximum Limit": "32000 characters"}

            ]


def campaigns():
    """

    :return: fields for campaigns module
    """
    return [{"Field Name": "Campaign Owner", "API FORMAT": "Campaign Owner",
             "Description": "SSelect the name of the user to whom the campaign is assigned.", "Data type": "Pick list",
             "Maximum Limit": "-"}, {"Field Name": "Campaign Name*", "API FORMAT": "Campaign Name*",
                                     "Description": "Specify the name of the campaign.", "Data type": "Text box",
                                     "Maximum Limit": "Alphanumeric(40)"},
            {"Field Name": "Type", "API FORMAT": "Type", "Description": "Select the type of the campaign.",
             "Data type": "Check box", "Maximum Limit": "-"},
            {"Field Name": "Status", "API FORMAT": "Status", "Description": "Select the status of the campaign.",
             "Data type": "Pick List", "Maximum Limit": "-"}, {"Field Name": "Start Date", "API FORMAT": "Start Date",
                                                               "Description": "Specify the date on which the campaign starts.",
                                                               "Data type": "Date format", "Maximum Limit": "-"},
            {"Field Name": "End Date", "API FORMAT": "End Date",
             "Description": "Specify the date on which the campaign ends.", "Data type": "Date format",
             "Maximum Limit": "-"}, {"Field Name": "Expected Revenue", "API FORMAT": "Expected Revenue",
                                     "Description": "Specify the revenue expected after launching the campaign.",
                                     "Data type": "Currency", "Maximum Limit": "-"},
            {"Field Name": "Actual Cost", "API FORMAT": "Actual Cost",
             "Description": "Specify the actual amount spent on the campaign.", "Data type": "Currency",
             "Maximum Limit": "-"}, {"Field Name": "Budgeted Cost", "API FORMAT": "Budgeted Cost",
                                     "Description": "Specify the planned amount to be spent on the campaign.",
                                     "Data type": "Currency", "Maximum Limit": "-"},
            {"Field Name": "Expected Response", "API FORMAT": "Expected Response",
             "Description": "Specify the campaign turnout percentage.", "Data type": "Number", "Maximum Limit": ""},
            {"Field Name": "Num sent", "API FORMAT": "Num sent",
             "Description": "Specify the number of leads/contacts to whom the campaign details has been sent.",
             "Data type": "Text box", "Maximum Limit": "Integers"},
            {"Field Name": "Description", "API FORMAT": "Description",
             "Description": "Specify additional details about the campaign.", "Data type": "Text area",
             "Maximum Limit": "32000 characters"}

            ]
